# Generated by Django 2.2.12 on 2020-06-24 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='first_para',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
